/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnimatedRing: typeof import('./src/components/AnimatedRing.vue')['default']
    BreakdownDashboard: typeof import('./src/components/BreakdownDashboard.vue')['default']
    CategoryCard: typeof import('./src/components/CategoryCard.vue')['default']
    IconMdiRecycle: typeof import('~icons/mdi/recycle')['default']
    ImpactCard: typeof import('./src/components/ImpactCard.vue')['default']
    ItemCard: typeof import('./src/components/ItemCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
