/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CategoryCard: typeof import('./src/components/CategoryCard.vue')['default']
    IconMdiArrowDownDropCircleOutline: typeof import('~icons/mdi/arrow-down-drop-circle-outline')['default']
    IconMdiFileExport: typeof import('~icons/mdi/file-export')['default']
    IconMdiLeaf: typeof import('~icons/mdi/leaf')['default']
    IconMdiRecycle: typeof import('~icons/mdi/recycle')['default']
    IconMdiUpload: typeof import('~icons/mdi/upload')['default']
    ImpactCard: typeof import('./src/components/ImpactCard.vue')['default']
    ItemCard: typeof import('./src/components/ItemCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatisticRing: typeof import('./src/components/StatisticRing.vue')['default']
  }
}
